# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane



default_platform(:ios)

platform :ios do
  desc "Build and upload Flutter app to TestFlight"
  lane :beta do
    
    sh "cd .. && flutter clean && flutter pub get"


    sh "cd .. && flutter build ios --release --no-simulator"

    build_ios_app(
      scheme: "Runner",          
      export_method: "app-store" 
    )

    # Upload to TestFlight
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      beta_app_review_info: {
        contact_email: "your_email@example.com",
        contact_first_name: "YourName",
        contact_last_name: "LastName",
        contact_phone: "+91 9876543210",
        demo_account_name: "demo@example.com",
        demo_account_password: "password123",
        notes: "Flutter iOS build uploaded from EC2 CI"
      }
    )
  end
end
