import 'package:flutter/material.dart';
import 'package:flutter_chat_ai/common_ui_components/cards/custom_user_profile_card.dart';
import 'package:flutter_chat_ai/common_ui_components/row/custom_row_layout.dart';
import 'package:flutter_chat_ai/features/profile/presentation/screens/opt_in_screen.dart';
import 'package:flutter_chat_ai/features/profile/presentation/screens/social_network_screen.dart';
import 'package:flutter_chat_ai/features/profile/presentation/widgets/skills_section.dart';
import 'package:flutter_chat_ai/main.dart';

class ProfileScreen extends StatelessWidget {
  const ProfileScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              crossAxisAlignment:  CrossAxisAlignment.center,
              children: [
                 Text(
                  "My Profile",
                  style: TextStyle(
                    fontSize: 20,
                    fontWeight: FontWeight.bold,
                    color: Theme.of(context).colorScheme.primary,
                  ),
                ),
                OutlinedButton(
                  style: OutlinedButton.styleFrom(
                    side: const BorderSide(color: Colors.black26),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(4),
                    ),
                    padding: const EdgeInsets.symmetric(vertical: 0, horizontal: 10),
                    alignment: Alignment.centerLeft,
                  ),
                  onPressed: () {
                    Navigator.pop(context);
                  },
                  child: const Text("Back to Chat", style: TextStyle(color: Colors.black87, fontSize: 12),),
                ),
              ],
            ),

             Text(
              "Manage your info, privacy and security settings to make Elysia work better for you",
              style: TextStyle(fontSize: 14, color: Theme.of(context).colorScheme.primaryContainer),
            ),
            const SizedBox(height: 12),

            CustomProfilePageCard(
              heading: "About",
              subheading: "This content was generated by Elysia based on your profile",
              sectionKey: "about",
              initialAboutMeContent:
              "Abirami Rajaram is a Senior Software Engineer at Tricon Infotech, based in Bengaluru, India. "
                  "They are an ambitious professional looking to grow their career towards becoming a successful Software Architect. "
                  "With experience in developing and maintaining iOS and Android mobile applications, Abirami has demonstrated proficiency "
                  "in various programming languages and technologies. They are a fast learner who has successfully built applications using "
                  "Flutter, DART, C#, C, C++, Java, and web technologies. Abirami’s expertise spans across mobile app development, REST API "
                  "creation, and end-to-end automation, showcasing their versatility in the software engineering field.",
            ),

            // CustomProfilePageCard(
            //   heading: "About",
            //   subheading:
            //   "This content was generated by Elysia based on your profile",
            //   child: const Text(
            //     "Abirami Rajaram is a Senior Software Engineer at Tricon Infotech, based in Bengaluru, India. "
            //         "They are an ambitious professional looking to grow their career towards becoming a successful Software Architect. "
            //         "With experience in developing and maintaining iOS and Android mobile applications, Abirami has demonstrated proficiency "
            //         "in various programming languages and technologies. They are a fast learner who has successfully built applications using "
            //         "Flutter, DART, C#, C, C++, Java, and web technologies. Abirami’s expertise spans across mobile app development, REST API "
            //         "creation, and end-to-end automation, showcasing their versatility in the software engineering field.",
            //     style: TextStyle(fontSize: 14, height: 1.4),
            //   ),
            // ),

            const SizedBox(height: 8),

            CustomProfilePageCard(
              heading: "Details",
              subheading: "This content was generated by Elysia based on your profile",
              child: Column(
                children: [
                  // Divider(height: 1, color: Colors.grey),
                  const CustomRowLayout(
                    label: "Full Name",
                    value: "Abirami Rajaram",
                  ),
                  const Divider(height: 1, color: Colors.black26),
                  const CustomRowLayout(
                    label: "Email",
                    value: "abirami.rajaram@informa.com",
                  ),
                  const Divider(height: 1, color: Colors.black26),
                  CustomRowLayout(
                    label: "Opt-In",
                    value: "Yes",
                    onTap: () async {
                      final result = await Navigator.push(
                        context,
                        MaterialPageRoute(
                          builder: (_) => const MainLayout(child: OptInScreen()),
                        ),
                      );
                      if (result != null) {
                        // handle Yes/No update here
                      }
                    },
                  ),
                  const Divider(height: 1, color: Colors.black26),
                  CustomRowLayout(
                    label: "Social Networks",
                    value: "LinkedIn",
                    onTap: () async {
                      final result = await Navigator.push(
                        context,
                        MaterialPageRoute(
                          builder: (_) => const MainLayout(child: SocialNetworkScreen()),
                        ),
                      );
                      if (result != null) {
                        // handle updated LinkedIn or other social network
                      }
                    },
                  ),
                  const Divider(height: 1, color: Colors.black26),
                ],
              ),
            ),

            // CustomProfilePageCard(
            //   heading: "Details",
            //   subheading:
            //   "This content was generated by Elysia based on your profile",
            //   child: Wrap(
            //     spacing: 8,
            //     runSpacing: 8,
            //     children: [
            //       Chip(label: Text("Flutter")),
            //       Chip(label: Text("Python")),
            //       Chip(label: Text("AWS")),
            //     ],
            //   ),
            // ),

            const SizedBox(height: 8),
            //
            // Skills Section
            CustomProfilePageCard(
              heading: "Skills",
              subheading: "This content was generated by Elysia based on your profile",
              child: const SkillsSection(),
            ),

            const SizedBox(height: 8),
            CustomProfilePageCard(
              heading: "Interests",
              subheading:
              "This content was generated by Elysia based on your profile",
              child: Wrap(
                spacing: 8,
                runSpacing: 8,
                children: [
                  Chip(label: Text("Flutter")),
                  Chip(label: Text("Python")),
                  Chip(label: Text("AWS")),
                ],
              ),
            ),


            // Interests Section
            // _buildChipsSection(
            //   title: "Interests",
            //   chips: [
            //     "Software Architecture",
            //     "Mobile App Development",
            //     "Cloud Computing",
            //     "DevOps",
            //     "UI/UX Design",
            //     "Emerging Technologies",
            //     "Agile Methodologies",
            //     "Cross-platform Development"
            //   ],
            // ),
          ],
        ),
      ),
    );
  }

  // Widget _buildCard({required String title, required String content}) {
  //   return Card(
  //     shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
  //     child: Padding(
  //       padding: const EdgeInsets.all(12.0),
  //       child: Column(
  //         crossAxisAlignment: CrossAxisAlignment.start,
  //         children: [
  //           Text(title,
  //               style: const TextStyle(
  //                   fontWeight: FontWeight.bold, fontSize: 16)),
  //           const SizedBox(height: 8),
  //           Text(content, style: const TextStyle(fontSize: 14)),
  //         ],
  //       ),
  //     ),
  //   );
  // }

  //
  // static Widget _buildDetailRow(String label, String value) {
  //   return Padding(
  //     padding: EdgeInsets.symmetric(vertical: 4.0),
  //     child: Row(
  //       children: [
  //         Expanded(
  //           flex: 2,
  //           child: Text(label,
  //               style: TextStyle(fontWeight: FontWeight.w500, fontSize: 14)),
  //         ),
  //         Expanded(
  //           flex: 3,
  //           child: Text(value, style: TextStyle(fontSize: 14)),
  //         ),
  //       ],
  //     ),
  //   );
  // }

}
