name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone Flutter SDK (3.27.2)
        run: |
          git clone https://github.com/flutter/flutter.git --branch 3.27.2 --depth 1 ~/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Run build (example APK build)
        run: flutter build apk --debug
